name: linux
on:
  - push
  - pull_request
jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo cpan Alien::Build PkgConfig Sort::Versions
      - run: perl Makefile.PL
      - run: make
      - run: make test TEST_VERBOSE=1
