name: windows

on:
  - push
  - pull_request

jobs:
  perl:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: cpan Alien::Build PkgConfig Sort::Versions App::pwhich
      - run: perl -V
      - run: pwhich perl
      - run: perl Makefile.PL
      - run: make
      - run: make test TEST_VERBOSE=1
